---

- hosts: all
  remote_user: ubuntu
  become: true
  tasks:

  - name: update cache
    apt:
      update_cache: yes

  - name: Install Apache2
    apt: 
      name:
        - apache2
      state: present

  - name: Set timezone to Africa/Lagos
    timezone:
      name: Africa/Lagos

  - name: Display hostname
    shell: echo "<h1>Welcome to my Page!! This is my ip $(hostname -f) and today's date in Lagos, Nigeria is $(date)</h1>" > /var/www/html/index.html
    notify: restart_apache

  handlers:
  - name: restart_apache
    systemd:
      name: apache2
      state: restarted
